%YAML:1.0
ImageSourceType: 'ImageSequence'
#ImageSourceType: 'ImagesBuffer'
TrackingType: 'ShapeSequence'
#TrackingType: 'ShapesBuffer'
ImageSourceSettings:
  dataPath: '/cvfish/home/Work/data/cvlab/kinect_tshirt/kinect_tshirt/photo_metric/fr1_to_313/'
  frameStep: 1
  numFrames: 313
  width: 640
  height: 480
ShapeLoadingSettings:
  resultsPath: '/cvfish/home/Work/data/cvlab/kinect_tshirt/kinect_tshirt/photo_metric/fr1_to_313/result/PM500_TV0_Deform0_Huber1_5_TVRef_Alter_CG_UseXYZ_Iter30_30_30_30_TransPrior0.01_RigidTracking/pangaea/'
  hasGT: 1
  loadShapeMask: 1
  shapeColMajor: 1
  shapeSamplingScale: 1
