%YAML:1.0
ImageSourceType: 'ImageSequence'
#ImageSourceType: 'ImagesBuffer'
TrackingType: 'ShapeSequence'
#TrackingType: 'ShapesBuffer'
ImageSourceSettings:
  dataPath: '/cvfish/home/Work/data/occlusion/'
  frameStep: 1
  numFrames: 1200
  width: 1280
  height: 720
  imageFormat: 'mask300_rgb%04d.png'
ShapeLoadingSettings:
  resultsPath: '/cvfish/home/Work/data/occlusion/result/occlusion_expr/PM500_TV0.5_Deform0_Huber1_5_TVRef_Alter_CG_UseXYZ_Iter30_30_30_5_5_Do3Levels_LLTImage_Out2_TVs0.25_0.5_1_1_1/pangaea/'
  hasGT: 0
  loadShapeMask: 1
  shapeColMajor: 1
  shapeSamplingScale: 0.25
