%YAML:1.0
ImageSourceType: 'ImageSequence'
#ImageSourceType: 'ImagesBuffer'
TrackingType: 'ShapeSequence'
#TrackingType: 'ShapesBuffer'
ImageSourceSettings:
  dataPath: '/home/cvfish/Work/data/pangaea_tracking_data/test/input/'
  numFrames: 5
  width: 1280
  height: 720
ShapeLoadingSettings:
  resultsPath: '/home/cvfish/Work/data/pangaea_tracking_data/test/result/'
  loadShapeMask: 1
  shapeColMajor: 1
  shapeSamplingScale: 0.25
