%YAML:1.0
ImageSourceType: 'ImageSequence'
#ImageSourceType: 'ImagesBuffer'
TrackingType: 'ShapeSequence'
#TrackingType: 'ShapesBuffer'
ImageSourceSettings:
  dataPath: '/cvfish/home/Work/data/noise/'
  frameStep: 1
  numFrames: 500
  width: 1920
  height: 1080
ShapeLoadingSettings:
  resultsPath: '/cvfish/home/Work/data/noise/result/PM500_TV0.5_Deform0_Huber0.1_1_TVRef_CG_UseXYZ_Iter30_30_30_5_5_Do2Levels_LLTImage_Out2_TVs0.03125_0.125_0.5_0.5_0.5_SNR-20/pangaea/'
  hasGT: 0
  loadShapeMask: 1
  shapeColMajor: 1
  shapeSamplingScale: 0.25
